USE ROLE ACCOUNTADMIN;

USE WAREHOUSE COMPUTE_WH;

USE SCHEMA EMP_ANALYTICS.BRONZE;

CREATE OR REPLACE TABLE raw_attendance (
    employee_id STRING,
    checkin_time TIMESTAMP,
    checkout_time TIMESTAMP,
    ingestion_ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);
