[project]
name = "employee-activity-intelligence"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "apache-airflow>=3.2.1",
    "dbt-core>=1.11.9",
    "dbt-snowflake>=1.11.4",
    "pandas>=3.0.3",
    "psycopg2-binary>=2.9.12",
    "snowflake-connector-python>=4.5.0",
    "snowflake-sqlalchemy>=1.9.0",
    "sqlalchemy>=2.0.49",
]
