USE ROLE ACCOUNTADMIN;

USE WAREHOUSE COMPUTE_WH;

CREATE OR REPLACE DATABASE EMP_ANALYTICS;

SHOW DATABASES;

CREATE SCHEMA EMP_ANALYTICS.BRONZE;
CREATE SCHEMA EMP_ANALYTICS.SILVER;
CREATE SCHEMA EMP_ANALYTICS.GOLD;
CREATE SCHEMA EMP_ANALYTICS.AUDIT;

USE SCHEMA EMP_ANALYTICS.BRONZE;